.gitmodules
content/en/docs/Access/Check in/checkin.md
content/en/docs/Access/Check out/checkout.md
content/en/docs/Access/Circulation log/circ_log.md
content/en/docs/Access/Courses/courses.md
content/en/docs/Access/Requests/requests.md
content/en/docs/Access/_index.md
content/en/docs/Administration/Settings/settings_circulation.md
content/en/docs/Administration/Settings/settings_courses.md

Resource access

---

content/en/docs/Getting started/Installation/singleserverwithcontainers.md

Hi @marciafolio , I have just tested the installation procedure for the single server with containers and added my changes to this Pull Request. 
Other persons of SysOps has also tested it and found similar things (installation of perl modules is missing, wrong filename to increase "max connections" - should be /etc/postgresql/10/main/postgresql.conf, unclear in which directory you are in in some points of this prescription, Okapi version was not up-to-date [Okapi couldn't pull modules]). I corrected all these mistakes/weaknesses in this PR.
Please consider merging this pull request and/or have it reviewed by one of the tech writers.

Tested single server installation procedure on a fresh Ubuntu 20 server

---

README.md

Adding a minimal example using Docker to README.md.

DOCS-27: Explain how to run Hugo locally

---

content/en/docs/Getting started/Installation/singleservernocontainers.md

This has been extracted from https://github.com/folio-org/docs/pull/4/commits/604930f2656601bc69d30ce9cc822be99e5ec15b

DOCS-19: Debian package recommendation: Not for a production system

---

content/en/docs/Acquisitions/Finance/_index.md

Update Finance info

---

content/en/docs/Acquisitions/Receiving/_index.md

Update Receiving info

---

content/en/docs/Settings/_index.md

Settings landing

---

content/en/docs/_index.md

Add version note to the home page.

Update home page with version

---

content/en/docs/Getting started/Installation/singleserverwithcontainers.md

Hi @marciafolio , I tested this for an R1-2021 installation of platform complete and it works.

R1-2021 single server installation prescription

---

content/en/docs/Getting started/Installation/singleservernocontainers.md

Updated the documentation on Deb installation (experimental); killed quite some errors and security issues and clarified stuff.

DebDepl_v0.2

---

content/en/docs/Metadata/Inventory/_index.md
content/en/docs/Metadata/Inventory/subtopic2.md
content/en/docs/Settings/Settings_inventory/Settings_inventory.md

adding content under Metadata Management > Inventory and Settings > Inventory. Also removing untitled subtopic under Metadata Management > Inventory.

Add Inventory content

---

content/en/docs/Access/Courses/courses.md

Fix serial comma issue

---

content/en/docs/Access/Check out/checkout.md

From SME feedback - adding additional context to "Assessing the patron's data"

Adding add'l context to Assessing Patron Data

---

content/en/docs/Access/Requests/requests.md

SME feedback - add'l context and fixing typos

SME feedback - add'l context and fixing typos

---

content/en/docs/Platform essentials/Locations/locations.md

Fixing numbered list formatting

Fixing numbered list formatting

---

content/en/docs/Platform essentials/Keyboard shortcuts/keyboardshortcuts.md

Fixing numbering in "Viewing the keyboard shortcuts list"

Fix numbering in viewing list

---

content/en/docs/Reporting/FOLIO Analytics/_index.md
content/en/docs/Reporting/LDLite/_index.md
content/en/docs/Reporting/Library Data Platform/_index.md
content/en/docs/Reporting/_index.md

- Updating of links and external documentation
- New LDLite page
- And some rephrasing

Reporting Docs Juniper

---

config.toml

Slack, Twitter, Discuss, GitHub
(cherry picked from commit 9f216a89ff99141716fb671a225cc5eb3ff44142)

Fix some icons and links on the footer

---

content/en/docs/Access/Courses/courses.md

Adding updates for Kiwi documentation for Courses.

Kiwi addcoursesupdates

---

content/en/docs/Reporting/LDP App/_index.md
content/en/docs/Reporting/ldpmarc/_index.md

- ldpmarc page -- fixing format of code block
- ldp app -- add alert about saving settings issue

Kiwi Reporting format fix & found issue

---

content/en/docs/Glossary/_index.md

Add a definition for "Analytic" to the glossary, provided by MM SIG member.

Add definition of "Analytic"

---

content/en/docs/Reporting/FOLIO Analytics/_index.md
content/en/docs/Reporting/LDP App/_index.md
content/en/docs/Reporting/Library Data Platform/_index.md
content/en/docs/Reporting/_index.md
content/en/docs/Reporting/ldpmarc/_index.md

Reporting updates for Lotus release

Lotus Reporting

---

content/en/docs/Reporting/LDP App/_index.md
content/en/docs/Reporting/ldpmarc/_index.md

- Fixes invalid relative link (correct for Hugo requirements instead of GitHub docs)
- Fixes spacing that caused link to not be hyperlink

Lotus Reporting minor updates for formatting

---

content/en/docs/Reporting/FOLIO Analytics/_index.md
content/en/docs/Reporting/LDLite/_index.md
content/en/docs/Reporting/LDP App/_index.md
content/en/docs/Reporting/Library Data Platform/_index.md

- update to version matrix
- few re-wordings and corrections

Lotus reporting updates

---

content/en/docs/Settings/System_software_versions/System_software_versions.md

(cherry picked from commit ae1e61d64df0341b20f9fe8dba909af4f4e5aeb6)

Lotus R1-2022-hotfix-2

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Add content to Patron ids and checkout scanning and fix formatting. Adding here for Lotus, will also be in Morning Glory. Reference DOCS-219

Add content to Patron ids and checkout scanning

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Includes minor content updates, formatting fixes, and a new section for Title Level Request settings.

Updates to Circulation settings doc for Morning Glory

---

content/en/docs/Getting started/Installation/customizations.md

I did edge module configuration with Andy Kim and we found some errors in the documentation.
These were due to the fact that alpine linux is running inside the stripes container, and not Ubuntu 20 as on the single server / PC.
So, the configuration of nginx is differernt inside the container as it would be on Ubuntu linux. These changes take care of this.
@sekjal

Change edge module nginx configuration prescription

---

content/en/docs/Access/Additional topics/loans/loans.md

Updating to remove Kiwi references since this is a Lotus doc.

Updating references to Kiwi/Lotus flower releases

---

content/en/docs/Access/Additional topics/loans/loans.md

Adding new loan troubleshooting section, removing references to Kiwi

Adding new section, updates to remove Kiwi ref

---

content/en/docs/Access/Requests/requests.md

Includes content for title-level requesting.

Requests documentation for MG

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Got my PRs mixed up and the new permissions didn't make it into the initial version, so adding now.

Adding permissions for settings_circulation

---

content/en/docs/Settings/Settings_remotestorage/remotestorage.md

Updates to Remote Storage settings labels and workflows for Nolana.

DOCS-213 - Remote Storage settings

---

content/en/docs/Platform essentials/Permissions/_index.md

Finally adding the Permissions section content to platform essentials.
This needs to go both to the Morning Glory and the Main branch.

Adding Permissions section to Platform Essentials

---

content/en/docs/Settings/System_software_versions/System_software_versions.md

This is for the lotus branch of the docs.

Add R2-2022-GA and R1-2022-hotfix-3 to flower releases list

---

content/en/docs/Settings/Settings_tags/Settings_tags.md

Adding content about allowed characters for tags for MG version.

DOCS-236 for Morning Glory

---

content/en/docs/Bulk Edit/_index.md

It was a new app in MG and added there, but this PR will add it to the Nolana branch.

Create the bulk edit folder for Nolana

---

content/en/docs/Platform essentials/Locations/locations.md

Link syntax was broken so small fix. Not sure if it's correct to push this to MG branch or if I should have done a PR against main - happy to do a different PR if necessary

Fix link to tenant settings

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Adding updates to permissions and other content fixes for Nolana.

Nolana settings circulation

---

content/en/docs/Access/Additional topics/loans/loans.md

Adding additional content for Nolana and updating to reflect work on policy dependencies.

Nolana addlinfo loans

---

content/en/docs/Access/Requests/requests.md

Remove reference to bug with queue numbers that has been fixed; added clarification about title-level requests requiring holdings records.

Nolana requests updates

---

content/en/docs/Settings/Settings_calendar/settings_calendar.md

Updates to reflect UI changes and other improvements for the calendar in Nolana.

Nolana calendar improvements

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Fix subheading that was copy-pasted wrong.

DOCS-278 Fix subheading

---

content/en/docs/Getting started/Installation/singleserverfreshinstall.md

This is my Christmas present to the FOLIO Community: A **tested** single-server fresh installation documentation for Nolana!

Update single server fresh install to Nolana

---

content/en/docs/Platform essentials/Permissions/_index.md

Fix formatting errors that got into this document - bulleted list was lost.

Fix bullet errors - Orchid

---

content/en/docs/Access/Courses/courses.md

Add more documentation re: use and function of course reserve copyright fields.

Add copyright info docs

---

content/en/docs/Platform essentials/Permissions/_index.md

Fix formatting in "What is a permission?"

Fix formatting

---

config.toml

baseURL = "https://morning-glory.docs.folio.org/"
title = "FOLIO Documentation - Morning Glory"

Setup baseURL and title for Nolana in config.toml

---

content/en/docs/Getting started/_index.md

(cherry picked from commit 92ba2799fb9e9a8e9c38ac2ae84a56f59ef4a0b9)

Update demo site links and show URL with flower name (Nolana)

---

assets/scss/_styles_project.scss
config.toml
layouts/partials/footer.html

At the request of the [Community Council](https://wiki.folio.org/display/CC/2023-02-13+Meeting+notes). Fixes DOCS-295

Change footer to use CC-By 4.0 and copyright held by FOLIO project

---

content/en/docs/Access/Check in/checkin.md
content/en/docs/Settings/Settings_tenant/Settings_tenant.md

Documentation for new feature to manage hold shelf expiration date.

DOCS-282: Hold shelf expiration and closed date

---

content/en/docs/Settings/Settings_circulation/settings_circulation.md

Various fixes / backports to Settings > Circulation for Nolana.

Updates to Settings > Circulation for Nolana

---

content/en/docs/Access/Check out/checkout.md

Add flag icon for when due date is sooner than expected. Ref UXPROD-2778

Add flag icon for due date change

---

content/en/docs/Access/Additional topics/feesfines/feesfines.md

Updates for new functionality, actual cost, tweaks and clarifications, remove reference to Kiwi.

Orchid feesfines

---

content/en/docs/Access/Courses/courses.md

Backport documentation on additional copyright info to Nolana.
Orchid PR: #189
Orchid commit: 3a4a4d7ad360515f9fcf476325ecc6f43ae32cb9

Backport docs on additional copyright info

---

content/en/docs/Acquisitions/Invoices/_index.md

Changes to the Invoices documentation for the Orchid release - DOCS-298 and DOCS-290

Update Acquisitions > Invoices for Orchid

---

content/en/docs/Export Manager/_index.md

content/en/docs/Export Manager/_index.md

Export manager updates for Orchid release

---

content/en/docs/Acquisitions/Finance/_index.md

Added over encumbrance and over expenditure to "view ledger" and "view group" sections as requested in DOCS-290

Update Acquisitions > Finance for Orchid

---

content/en/docs/Acquisitions/Receiving/_index.md

Corrected step #2 in the receiving title section to add the new Action button as requested in DOCS-290

Update Acquisitions > Receiving for Orchid

---

content/en/docs/Access/Additional topics/feesfines/feesfines.md

With actual cost you can now age something to lost without having to charge a fine -  adding it to questions.

Add how to age to lost without charge
